# ----- Model Options -----
model_arch                  : Dilated10ConvAttentionMap1x1AvgTauResNet34WithSparsity2
scale_arch                  : LinearScaleClassifier
freeze_model                : False
ndf                         : 64
nc                          : 3
attention_sparsity          : 0.07
attention_sparsity_r        : 20

# =======================================
#   TRAINING OPTIONS
batch_size                  : 32
lr                          : 0.0002
momentum                    : 0.9
weight_decay                : 0.0001
n_epochs                    : 10000
losses                      : ['scale', 'smooth_att', 'equiv_aug_mse']
predictions                 : ['scale']
checkpoint_special          : 1
lr_decay                    : 0.1
lr_decay_every              : [300, 600]

scale_scale                 : 1.0

equivariance_scale          : False
equivariance_aug            : ['FX', 'FY', 'TR', 'R90', 'R180', 'R270']
optimiser                   : adam

# =======================================

# Natural images (ImageNet)
pixel_means                 : [0.485, 0.456, 0.406]
pixel_stds                  : [0.229, 0.224, 0.225]

max_train_batches_per_epoch : 100
max_val_batches_per_epoch   : 5
use_colour_transform        : True
use_image_transforms        : True


# DATASET OPTIONS

image_size                  : 224
patch_size                  : 160
workers                     : 8
dset_name                   : monuseg_wsi
dataroot                    : /pocket2/mihir/monuseg_tiles_224x224/
stain_normaliser_file       : stain_normalisation_target.png
hed_decomp                  : False
hed_channels                : [0, 1, 2]
seg_threshold               : 0.9
levels                      : ['-2', '-1', 'max']
splits_file                 : splits.yaml


# OTHER OPTIONS
load                        : '' 
init_model                  : ''
